//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _CAMERASERVICEIN_UPCALL_MANAGER_HH
#define _CAMERASERVICEIN_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "CameraServiceInUpcallInterface.hh"

/** CameraServiceInUpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort CameraServiceIn and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class CameraServiceInUpcallManager
:	public Smart::IInputHandler<DomainVision::CommVideoImage>
{
private:
	// list of associated updalls
	std::list<CameraServiceInUpcallInterface*> upcalls;

	// call the on_CameraServiceIn of all the attached CameraServiceInUpcallInterfaces
	void notify_upcalls(const DomainVision::CommVideoImage &input);
	
protected:
	virtual void handle_input(const DomainVision::CommVideoImage &input) {
		// relay input-handling to all attached CameraServiceInUpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	CameraServiceInUpcallManager(
		Smart::InputSubject<DomainVision::CommVideoImage> *subject,
		const int &prescaleFactor=1
	);
	virtual ~CameraServiceInUpcallManager();
	
	void attach(CameraServiceInUpcallInterface *upcall);
	void detach(CameraServiceInUpcallInterface *upcall);
};

#endif
