//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef SMARTEMOTIONRECOGNITION_ACE_PORTFACTORY_HH_
#define SMARTEMOTIONRECOGNITION_ACE_PORTFACTORY_HH_

// include ACE/SmartSoft component implementation
#include "SmartEmotionRecognitionImpl.hh"

// include the main component-definition class
#include "SmartEmotionRecognitionPortFactoryInterface.hh"

class SmartEmotionRecognitionAcePortFactory: public SmartEmotionRecognitionPortFactoryInterface
{
private:
	SmartEmotionRecognitionImpl *componentImpl;
public:
	SmartEmotionRecognitionAcePortFactory();
	virtual ~SmartEmotionRecognitionAcePortFactory();

	virtual void initialize(SmartEmotionRecognition *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	virtual Smart::IPushClientPattern<DomainVision::CommVideoImage> * createCameraServiceIn() override;
	
	virtual Smart::IEventServerPattern<CommBasicObjects::CommVoid, CommObjectRecognitionObjects::CommObjectRecognitionEventResult, CommObjectRecognitionObjects::CommObjectRecognitionEventState> * createEmotionEventServiceOut(const std::string &serviceName, std::shared_ptr<Smart::IEventTestHandler<CommBasicObjects::CommVoid, CommObjectRecognitionObjects::CommObjectRecognitionEventResult, CommObjectRecognitionObjects::CommObjectRecognitionEventState>> emotionEventServiceOutEventTestHandler) override;
	virtual Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties> * createEmotionQueryServiceAnsw(const std::string &serviceName) override;
	virtual Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionEnvironment> * createEnvironmentQueryServiceAnsw(const std::string &serviceName) override;
	
	// get a pointer to the internal component implementation
	SmartACE::SmartComponent* getComponentImpl();

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* SMARTEMOTIONRECOGNITION_ACE_PORTFACTORY_HH_ */
