//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "SmartEmotionRecognitionAcePortFactory.hh"

// create a static instance of the default AcePortFactory
static SmartEmotionRecognitionAcePortFactory acePortFactory;

SmartEmotionRecognitionAcePortFactory::SmartEmotionRecognitionAcePortFactory()
{  
	componentImpl = 0;
	SmartEmotionRecognition::instance()->addPortFactory("ACE_SmartSoft", this);
}

SmartEmotionRecognitionAcePortFactory::~SmartEmotionRecognitionAcePortFactory()
{  }

void SmartEmotionRecognitionAcePortFactory::initialize(SmartEmotionRecognition *component, int argc, char* argv[])
{
	if(component->connections.component.defaultScheduler != "DEFAULT") {
		ACE_Sched_Params sched_params(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(component->connections.component.defaultScheduler == "FIFO") {
			sched_params.policy(ACE_SCHED_FIFO);
			sched_params.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(component->connections.component.defaultScheduler == "RR") {
			sched_params.policy(ACE_SCHED_RR);
			sched_params.priority(ACE_THR_PRI_RR_MIN);
		}
		// create new instance of the SmartSoft component with customized scheuling parameters 
		componentImpl = new SmartEmotionRecognitionImpl(component->connections.component.name, argc, argv, sched_params);
	} else {
		// create new instance of the SmartSoft component
		componentImpl = new SmartEmotionRecognitionImpl(component->connections.component.name, argc, argv);
	}
}

int SmartEmotionRecognitionAcePortFactory::onStartup()
{
	return componentImpl->startComponentInfrastructure();
}

Smart::IPushClientPattern<DomainVision::CommVideoImage> * SmartEmotionRecognitionAcePortFactory::createCameraServiceIn()
{
	return new SmartACE::PushClient<DomainVision::CommVideoImage>(componentImpl);
}


Smart::IEventServerPattern<CommBasicObjects::CommVoid, CommObjectRecognitionObjects::CommObjectRecognitionEventResult, CommObjectRecognitionObjects::CommObjectRecognitionEventState> * SmartEmotionRecognitionAcePortFactory::createEmotionEventServiceOut(const std::string &serviceName, std::shared_ptr<Smart::IEventTestHandler<CommBasicObjects::CommVoid, CommObjectRecognitionObjects::CommObjectRecognitionEventResult, CommObjectRecognitionObjects::CommObjectRecognitionEventState>> emotionEventServiceOutEventTestHandler)
{
	return new SmartACE::EventServer<CommBasicObjects::CommVoid, CommObjectRecognitionObjects::CommObjectRecognitionEventResult, CommObjectRecognitionObjects::CommObjectRecognitionEventState>(componentImpl, serviceName, emotionEventServiceOutEventTestHandler);
}

Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties> * SmartEmotionRecognitionAcePortFactory::createEmotionQueryServiceAnsw(const std::string &serviceName)
{
	return new SmartACE::QueryServer<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties>(componentImpl, serviceName);
}

Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionEnvironment> * SmartEmotionRecognitionAcePortFactory::createEnvironmentQueryServiceAnsw(const std::string &serviceName)
{
	return new SmartACE::QueryServer<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionEnvironment>(componentImpl, serviceName);
}


SmartACE::SmartComponent* SmartEmotionRecognitionAcePortFactory::getComponentImpl()
{
	return componentImpl;
}

int SmartEmotionRecognitionAcePortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	componentImpl->stopComponentInfrastructure(timeoutTime);
	return 0;
}

void SmartEmotionRecognitionAcePortFactory::destroy()
{
	// clean-up component's internally used resources (internally used communication middleware) 
	componentImpl->cleanUpComponentResources();
	delete componentImpl;
}
