//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _SMARTEMOTIONRECOGNITION_HH
#define _SMARTEMOTIONRECOGNITION_HH

#include <map>
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "SmartEmotionRecognitionCore.hh"

#include "SmartEmotionRecognitionPortFactoryInterface.hh"
#include "SmartEmotionRecognitionExtension.hh"

// forward declarations
class SmartEmotionRecognitionPortFactoryInterface;
class SmartEmotionRecognitionExtension;

// includes for OpcUaBackendComponentGeneratorExtension

// includes for PlainOpcUaSmartEmotionRecognitionExtension
// include plain OPC UA device clients
// include plain OPC UA status servers

// includes for SmartEmotionRecognitionROSExtension


// include communication objects
#include <CommObjectRecognitionObjects/CommObjectRecognitionEnvironment.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionEnvironmentACE.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionEventResult.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionEventResultACE.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionEventState.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionEventStateACE.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionId.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionIdACE.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionObjectProperties.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionObjectPropertiesACE.hh>
#include <DomainVision/CommVideoImage.hh>
#include <DomainVision/CommVideoImageACE.hh>
#include <CommBasicObjects/CommVoid.hh>
#include <CommBasicObjects/CommVoidACE.hh>

// include tasks
#include "CaptureTask.hh"
#include "RecognitionTask.hh"
// include UpcallManagers
#include "CameraServiceInUpcallManager.hh"

// include input-handler(s)
// include request-handler(s)
#include "EmotionQueryServiceAnswHandler.hh"
#include "EnvironmentQueryServiceAnswHandler.hh"

// include handler
#include "CompHandler.hh"

#include "ParameterStateStruct.hh"
#include "ParameterUpdateHandler.hh"

#include "SmartStateChangeHandler.hh"

#define COMP SmartEmotionRecognition::instance()

class SmartEmotionRecognition : public SmartEmotionRecognitionCore {
private:
	static SmartEmotionRecognition *_smartEmotionRecognition;
	
	// constructor
	SmartEmotionRecognition();
	
	// copy-constructor
	SmartEmotionRecognition(const SmartEmotionRecognition& cc);
	
	// destructor
	~SmartEmotionRecognition() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	// helper method that maps a string-name to an according TaskTriggerSubject
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
	// internal map storing the different port-creation factories (that internally map to specific middleware implementations)
	std::map<std::string, SmartEmotionRecognitionPortFactoryInterface*> portFactoryRegistry;
	
	// internal map storing various extensions of this component class
	std::map<std::string, SmartEmotionRecognitionExtension*> componentExtensionRegistry;
	
public:
	ParameterStateStruct getGlobalState() const
	{
		return paramHandler.getGlobalState();
	}
	
	ParameterStateStruct getParameters() const
	{
		return paramHandler.getGlobalState();
	}
	
	// define tasks
	Smart::TaskTriggerSubject* captureTaskTrigger;
	CaptureTask *captureTask;
	Smart::TaskTriggerSubject* recognitionTaskTrigger;
	RecognitionTask *recognitionTask;
	
	// define input-ports
	// InputPort CameraServiceIn
	Smart::IPushClientPattern<DomainVision::CommVideoImage> *cameraServiceIn;
	Smart::InputTaskTrigger<DomainVision::CommVideoImage> *cameraServiceInInputTaskTrigger;
	CameraServiceInUpcallManager *cameraServiceInUpcallManager;
	
	// define request-ports
	
	// define input-handler
	
	// define output-ports
	Smart::IEventServerPattern<CommBasicObjects::CommVoid, CommObjectRecognitionObjects::CommObjectRecognitionEventResult, CommObjectRecognitionObjects::CommObjectRecognitionEventState> *emotionEventServiceOut;
	std::shared_ptr<Smart::IEventTestHandler<CommBasicObjects::CommVoid, CommObjectRecognitionObjects::CommObjectRecognitionEventResult, CommObjectRecognitionObjects::CommObjectRecognitionEventState>> emotionEventServiceOutEventTestHandler;
	
	// define answer-ports
	Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties> *emotionQueryServiceAnsw;
	Smart::QueryServerTaskTrigger<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties> *emotionQueryServiceAnswInputTaskTrigger;
	Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionEnvironment> *environmentQueryServiceAnsw;
	Smart::QueryServerTaskTrigger<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionEnvironment> *environmentQueryServiceAnswInputTaskTrigger;
	
	// define request-handlers
	EmotionQueryServiceAnswHandler *emotionQueryServiceAnswHandler;
	EnvironmentQueryServiceAnswHandler *environmentQueryServiceAnswHandler;
	
	// definitions of OpcUaBackendComponentGeneratorExtension
	
	// definitions of PlainOpcUaSmartEmotionRecognitionExtension
	
	// definitions of SmartEmotionRecognitionROSExtension
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	ParamUpdateHandler paramHandler;
	SmartACE::ParameterSlave *param;
	
	
	/// this method is used to register different PortFactory classes (one for each supported middleware framework)
	void addPortFactory(const std::string &name, SmartEmotionRecognitionPortFactoryInterface *portFactory);
	
	SmartACE::SmartComponent* getComponentImpl();
	
	/// this method is used to register different component-extension classes
	void addExtension(SmartEmotionRecognitionExtension *extension);
	
	/// this method allows to access the registered component-extensions (automatically converting to the actuall implementation type)
	template <typename T>
	T* getExtension(const std::string &name) {
		auto it = componentExtensionRegistry.find(name);
		if(it != componentExtensionRegistry.end()) {
			return dynamic_cast<T*>(it->second);
		}
		return 0;
	}
	
	/// initialize component's internal members
	void init(int argc, char *argv[]);
	
	/// execute the component's infrastructure
	void run();
	
	/// clean-up component's resources
	void fini();
	
	/// call this method to set the overall component into the Alive state (i.e. component is then ready to operate)
	void setStartupFinished();
	
	/// connect all component's client ports
	Smart::StatusCode connectAndStartAllServices();
	
	/// start all assocuated Activities
	void startAllTasks();
	
	/// start all associated timers
	void startAllTimers();
	
	Smart::StatusCode connectCameraServiceIn(const std::string &serverName, const std::string &serviceName);

	// return singleton instance
	static SmartEmotionRecognition* instance()
	{
		if(_smartEmotionRecognition == 0) {
			_smartEmotionRecognition = new SmartEmotionRecognition();
		}
		return _smartEmotionRecognition;
	}
	
	static void deleteInstance() {
		if(_smartEmotionRecognition != 0) {
			delete _smartEmotionRecognition;
		}
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct CaptureTask_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} captureTask;
		struct RecognitionTask_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} recognitionTask;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
		struct EmotionEventServiceOut_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} emotionEventServiceOut;
		struct EmotionQueryServiceAnsw_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} emotionQueryServiceAnsw;
		struct EnvironmentQueryServiceAnsw_struct {
				std::string serviceName;
				std::string roboticMiddleware;
		} environmentQueryServiceAnsw;
	
		//--- client port parameter ---
		struct CameraServiceIn_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
			std::string roboticMiddleware;
		} cameraServiceIn;
		
		// -- parameters for OpcUaBackendComponentGeneratorExtension
		
		// -- parameters for PlainOpcUaSmartEmotionRecognitionExtension
		
		// -- parameters for SmartEmotionRecognitionROSExtension
		
	} connections;
};
#endif
